### PR TITLE
bump octet

### PR DESCRIPTION
**Pull request by tunnckoCore**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
need publish

**Comment by tunnckoCore** [comment]
@RobLoach ... was not needed v2. octet changes have no impact when using the jstransformer. it accepts same arguments and same positions, that's why i updated all of them (es6-template, octet and j140) to have same APIs and READMEs. And pass directly their `.compile` method jstransformer's compile.
There's no matter even if octet or others are v10, when they accepts and returns the same things and same types of arguments, and exactly what jstransformer needs. And as you can see, there's no tests changes.

[octet's changelog](https://github.com/tunnckoCore/octet/blob/master/CHANGELOG.md#300---2015-09-24) - you had to look it first.. and think for a second.

Absolute broke of semver for me, but.. yea, i dont love it so much. Nevermind, it is past. :)

**Comment by RobLoach** [comment]
It was a new major version of octet, so that could have breaking backwards compatibility changes in jstransformer-octet. SemVer states when there could be backward compatibilty changes, bump it up.

If there aren't any breaking changes, then just a minor version up is better.

**Comment by tunnckoCore** [comment]
Could, but don't have. Just think it. There have breaking changes for `octet` itself. In the context when you just using `octet`, because the changes stated in it's changelog - and actually, only the async api was dropped (so sync api which was used here still works, without any changes here). When user use it from the jstransformer there's no breaking changes, and in part that's all the idea behind wrappers like JSTransformer - for me. That's the beauty of these wrappers. In the context when using it through jstransformer there's no breaking changes and do the same thing and tests passes. If there was breaking changes  `jstransformer-octet` tests would fail.

**Comment by tunnckoCore** [comment]
Even, if i did not update `jstransformer-octet` index.js and only bumping octet to v3, the tests of `jstransformer-octet` all will work as expected, because `octet()` (the main exported function) works as .render by default, which was used in index.js

You can't have breaking changes in `jstransformer-<name>` itself, no matter using it with or without `jstransformer` even if `<name>` is v22.

Breaking change for some `jstransformer-*` and bumping it's major version, will mean that something in the `jstransformer` API is changed and this change will affect/break most of (or all) the transformers.

**Pull request merged**
